package render

import (
	"bytes"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"text/template"

	"squire/internal/config"
	"squire/internal/guide"
	"squire/internal/project"
)

const ManagedMarker = "squire:managed"

var managedComponentsRe = regexp.MustCompile(`<!--\s*squire:managed\b[^>]*\bcomponents=([a-zA-Z0-9_.:-]*(?:,[a-zA-Z0-9_.:-]+)*)[^>]*-->`)

type Context struct {
	Config    config.Config
	Project   project.Info
	Tools     []config.ToolConfig
	Preserved map[string]string
}

func Agents(cfg config.Config, projectInfo project.Info, preserved map[string]string) (string, error) {
	ctx := newContext(cfg, projectInfo, preserved)
	var out strings.Builder
	out.WriteString(managedComment(guide.AgentsFile, projectInfo.Components))
	out.WriteString("# " + projectInfo.Name + " Agent Guide\n\n")
	out.WriteString("Generated by Squire. Keep markers for analysis/regeneration.\n\n")

	for _, section := range guide.AgentSections() {
		rendered, err := renderSection(section, ctx)
		if err != nil {
			return "", err
		}
		out.WriteString(rendered)
		out.WriteString("\n")
	}

	return ensureTrailingNewline(out.String()), nil
}

func Claude(cfg config.Config, projectInfo project.Info, preserved map[string]string) (string, error) {
	ctx := newContext(cfg, projectInfo, preserved)
	var out strings.Builder
	out.WriteString(managedComment(guide.ClaudeFile, projectInfo.Components))
	out.WriteString("@AGENTS.md\n\n")
	out.WriteString("# " + projectInfo.Name + " Claude Code Guide\n\n")
	out.WriteString("Shared guidance: `AGENTS.md`. Claude-specific notes below.\n\n")

	for _, section := range guide.ClaudeSections() {
		rendered, err := renderSection(section, ctx)
		if err != nil {
			return "", err
		}
		out.WriteString(rendered)
		out.WriteString("\n")
	}

	return ensureTrailingNewline(out.String()), nil
}

func IsManaged(body []byte) bool {
	return bytes.Contains(body, []byte(ManagedMarker))
}

func ManagedComponents(body []byte) []string {
	match := managedComponentsRe.FindSubmatch(body)
	if len(match) != 2 {
		return nil
	}
	return splitComponents(string(match[1]))
}

func managedComment(file string, components []string) string {
	return fmt.Sprintf("<!-- %s file=%s components=%s -->\n", ManagedMarker, file, strings.Join(cleanComponents(components), ","))
}

func splitComponents(value string) []string {
	return cleanComponents(strings.Split(value, ","))
}

func cleanComponents(components []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, component := range components {
		component = strings.TrimSpace(component)
		if component == "" || seen[component] {
			continue
		}
		seen[component] = true
		out = append(out, component)
	}
	sort.Strings(out)
	return out
}

func PreservedSections(body []byte) map[string]string {
	out := map[string]string{}
	for _, section := range guide.AgentSections() {
		if !section.Preserved {
			continue
		}
		if body := sectionBody(string(body), section.ID); body != "" {
			out[section.ID] = body
		}
	}
	for _, section := range guide.ClaudeSections() {
		if !section.Preserved {
			continue
		}
		if body := sectionBody(string(body), section.ID); body != "" {
			out[section.ID] = body
		}
	}
	return out
}

func newContext(cfg config.Config, projectInfo project.Info, preserved map[string]string) Context {
	return Context{
		Config:    cfg,
		Project:   projectInfo,
		Tools:     config.MergeTools(cfg.CLITools, projectInfo.Tools),
		Preserved: preserved,
	}
}

func renderSection(section guide.Section, ctx Context) (string, error) {
	var body string
	if section.Preserved {
		body = strings.TrimSpace(ctx.Preserved[section.ID])
	}
	if body == "" {
		var err error
		body, err = executeTemplate(section.ID, section.Body, ctx)
		if err != nil {
			return "", err
		}
	}

	body = strings.TrimSpace(body)
	if body == "" {
		body = "- No guidance configured yet."
	}

	var out strings.Builder
	out.WriteString(fmt.Sprintf("<!-- squire:start id=%s required=%t preserved=%t -->\n", section.ID, section.Required, section.Preserved))
	out.WriteString("## " + section.Title + "\n\n")
	out.WriteString(body)
	out.WriteString("\n")
	out.WriteString(fmt.Sprintf("<!-- squire:end id=%s -->\n", section.ID))
	return out.String(), nil
}

func sectionBody(content, id string) string {
	startPattern := fmt.Sprintf(`<!--\s*squire:start\s+id=%s\b[^>]*-->`, regexp.QuoteMeta(id))
	endPattern := fmt.Sprintf(`<!--\s*squire:end\s+id=%s\s*-->`, regexp.QuoteMeta(id))
	startRe := regexp.MustCompile(startPattern)
	endRe := regexp.MustCompile(endPattern)

	start := startRe.FindStringIndex(content)
	if start == nil {
		return ""
	}
	afterStart := content[start[1]:]
	end := endRe.FindStringIndex(afterStart)
	if end == nil {
		return ""
	}

	inner := afterStart[:end[0]]
	lines := strings.Split(strings.TrimSpace(inner), "\n")
	if len(lines) >= 2 && strings.HasPrefix(strings.TrimSpace(lines[0]), "## ") {
		lines = lines[1:]
	}
	return strings.TrimSpace(strings.Join(lines, "\n"))
}

func executeTemplate(name, body string, ctx Context) (string, error) {
	tpl, err := template.New(name).Funcs(template.FuncMap{
		"bullets":  bullets,
		"commands": commands,
		"tools":    tools,
	}).Parse(body)
	if err != nil {
		return "", err
	}

	var out strings.Builder
	if err := tpl.Execute(&out, ctx); err != nil {
		return "", err
	}
	return out.String(), nil
}

func bullets(items []string) string {
	if len(items) == 0 {
		return "- No guidance configured yet."
	}
	var out strings.Builder
	for _, item := range items {
		item = strings.TrimSpace(item)
		if item == "" {
			continue
		}
		out.WriteString("- " + item + "\n")
	}
	return strings.TrimRight(out.String(), "\n")
}

func commands(items []project.Command) string {
	if len(items) == 0 {
		return "- Add setup, development, test, lint, and build commands for this project."
	}
	var out strings.Builder
	for _, item := range items {
		command := strings.TrimSpace(item.Command)
		if command == "" {
			continue
		}
		description := strings.TrimSpace(item.Description)
		if description == "" {
			out.WriteString("- `" + command + "`\n")
			continue
		}
		out.WriteString("- `" + command + "`: " + strings.TrimSuffix(description, ".") + "\n")
	}
	return strings.TrimRight(out.String(), "\n")
}

func tools(items []config.ToolConfig) string {
	if len(items) == 0 {
		return "- Add project-specific CLI tools with `squire cli add`."
	}

	sorted := append([]config.ToolConfig(nil), items...)
	sort.SliceStable(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	var out strings.Builder
	for _, item := range sorted {
		name := strings.TrimSpace(item.Name)
		command := strings.TrimSpace(item.Command)
		if name == "" {
			continue
		}
		if command == "" {
			command = name
		}
		line := "- `" + name + "` (`" + command + "`)"
		if item.Description != "" {
			line += ": " + strings.TrimSuffix(item.Description, ".")
		}
		if item.When != "" {
			line += "; " + strings.TrimSuffix(item.When, ".")
		}
		if len(item.Examples) > 0 {
			examples := make([]string, 0, len(item.Examples))
			for _, example := range item.Examples {
				example = strings.TrimSpace(example)
				if example != "" {
					examples = append(examples, "`"+example+"`")
				}
			}
			if len(examples) > 0 {
				line += "; examples: " + strings.Join(examples, ", ")
			}
		}
		out.WriteString(line + "\n")
	}
	return strings.TrimRight(out.String(), "\n")
}

func ensureTrailingNewline(value string) string {
	return strings.TrimRight(value, "\n") + "\n"
}
